apiVersion: v1
kind: Endpoints
metadata:
  name: awx
subsets:
- addresses:
  - ip: 192.168.4.214
  ports:
  - name: http
    port: 30080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: awx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx
spec:
  rules:
  - host: awx.pajos.us
    http:
      paths:
      - backend:
          service:
            name: awx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
