{{- range .Values.services }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
subsets:
- addresses:
{{- range .endpoint.addresses }}
  - ip: {{ . }}
{{- end }}
  ports:
{{- range .endpoint.ports }}
  - name: {{ .name }}
    port: {{ .number }}
    protocol: TCP
{{- end }}
{{- end }}