{{- range .Values.services }}
---
{{- $svcname := .name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  rules:
{{- range .service.ports }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $svcname }}
            port:
              number: {{ .number }}
        path: /
        pathType: ImplementationSpecific
{{- end }}
{{- end }}