apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
subsets:
- addresses:
  - ip: 192.168.4.98
  ports:
  - name: https
    port: 8006
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: ingress-proxmox@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: proxmox
spec:
  rules:
  - host: pve.pajos.us
    http:
      paths:
      - backend:
          service:
            name: proxmox
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
