{{ define "libchart.configmaps" }}
{{- range .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end}}
{{ end }}