{{- define "libchart.configmap" }}
{{- range .Values.configmaps }}
{{- with . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
---
{{- end -}}
{{ end -}}