{{- define "libchart.cronjob" }}
{{- range .Values.cronjobs }}
{{- with . }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ $.Chart.Name }}
          restartPolicy: Never
          containers:
          {{- range .containers }}
            {{- with . }}
            - name: {{ .name }}
              image: {{ .image.name }}:{{ .image.tag }}
              imagePullPolicy: {{ default "IfNotPresent" .image.pullPolicy }}
              {{- if .command }}
              command: 
              {{- range $key := .command }}
              - {{ $key }}
              {{- end }}
              {{- end }}
              {{- if .args }}
              args:
              {{- range $key := .args }}
              - {{ $key }}
              {{- end }}
              {{- end }}
              {{- if or .configmapref .secretref }}
              envFrom:
              {{- if .configmapref }}
              - configMapRef:
                  name: {{ $.Chart.Name }}-{{ .name }}
              {{- end }}
              {{- if .secretref }}
              - secretRef:
                  name: {{ $.Chart.Name }}-{{ .name }}
              {{- end }}
              {{- end }}
              {{- if .env }}
              env:
              {{- range $key, $value := .env }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
              {{- end }}
              {{- if .volumemounts }}
              volumeMounts:
              {{- range .volumemounts }}
              {{- with .}}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
              {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .volumes }}
          volumes:
          {{- range .volumes}}
            {{- with . }}
            - name: {{ .name }}
              hostPath:
                path: {{ .hostpath }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if .tolerations }}
          tolerations:
          {{- range .tolerations }}
            {{- with . }}
            - key: {{ .key }}
              operator: {{ .operator }}
              {{- if .value }}
              value: {{ .value }}
              {{- end }}
              effect: {{ .effect }}
            {{- end }}
          {{- end -}}
          {{- end }}
{{- end }}
---
{{- end -}}
{{ end -}}