{{- define "libchart.deployment" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "libchart.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "libchart.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "libchart.labels" . | indent 8 }}
    spec:
      {{- if .hostnetwork }}
      hostNetwork: {{ .hostnetwork }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}
      containers:
{{- include "libchart.containers" . | indent 6 }}
      {{- if .volumes }}
      volumes:
{{ toYaml .volumes | indent 8 }}
      {{- end }}
---
{{ include "libchart.service" . | trim }}
---
{{ include "libchart.pdb" . | trim }}
{{ end -}}