{{- define "libchart.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .Values.hostnetwork }}
      hostNetwork: {{ .Values.hostnetwork }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      containers:
      {{- range .Values.containers }}
        {{- with . }}
        - name: {{ .name }}
          image: {{ .image.name }}:{{ .image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .image.pullPolicy }}
          {{- if .args }}
          args:
          {{- range $key := .args }}
          - {{ $key }}
          {{- end }}
          {{- end }}
          {{- if .port }}
          ports:
          - name: {{ .port.name }}
            containerPort: {{ .port.num }}
            protocol: {{ .port.type }}
          {{- end }}
          {{- if or .configmapref .secretref }}
          envFrom:
          {{- if .configmapref }}
          - configMapRef:
              name: {{ $.Chart.Name }}-{{ .name }}
          {{- end }}
          {{- if .secretref }}
          - secretRef:
              name: {{ $.Chart.Name }}-{{ .name }}
          {{- end }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- range .volumeMounts }}
            {{- with .}}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end -}}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
{{ toYaml .readinessProbe | indent 12 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
{{ toYaml .livenessProbe | indent 12 }}
          {{- end }}
          {{- if .startupProbe }}
          startupProbe:
{{ toYaml .startupProbe | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
        {{- with . }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostpath }}
        {{- end }}
      {{- end -}}
      {{- end }}
{{ end -}}