{{- define "libchart.secret" }}
{{- range .Values.secrets }}
{{- with . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
type: Opaque
data:
{{- range $key, $value := .data }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}
---
{{- end -}}
{{ end -}}