{{- define "libchart.service" }}
{{- range .Values.services }}
{{- with . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: {{ default "ClusterIP" .type }}
  ports:
  - port: {{ required "value '.port' is required" .port }}
    targetPort: {{ required "value '.targetport' is required" .targetport }}
    protocol: TCP
    name: {{ .name }}
  selector:
    app: {{ $.Chart.Name }}
{{- end }}
---
{{- end -}}
{{ end -}}