{{- define "libchart.serviceaccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
 name: {{ .Chart.Name }}
automountServiceAccountToken: true
{{- if .Values.serviceaccount.k8spodexec }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-pod-list-exec
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: k8spodexec-list-exec
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{ end -}}