firefly-iii-stack:
  firefly-db:
    enabled: false
  firefly-iii:
    persistence:
      storageClassName: pinas-nfs-client
    extraVolumes:
    - name: db
      persistentVolumeClaim:
        claimName: firefly-db
    extraVolumeMounts:
    - mountPath: /var/www/html/storage/database
      name: db
    config:
      env:
        DEFAULT_LANGUAGE: "en_US"
        DEFAULT_LOCALE: "equal"
        TZ: "America/Phoenix"
        TRUSTED_PROXIES: "**"
        DB_CONNECTION: "sqlite"
    cronjob:
      enabled: true
    ingress:
      enabled: true
      hosts:
      - budget.pajos.us
  importer:
    fireflyiii:
      vanityUrl: "https://budget.pajos.us"
    config:
      env:
        IGNORE_DUPLICATE_ERRORS: "false"
        TZ: "America/Phoenix"
