apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-vault-annotations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    policies.kyverno.io/title: Add Vault annotation
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Annotation
    policies.kyverno.io/description: >-
      Add vault annotation to configmap, secret and pod
spec:
  rules:
  - name: add-vault-annotations
    match:
      resources:
        kinds:
        - ConfigMap
        - Secret
        - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            vault.security.banzaicloud.io/vault-role: >-
              {{ printf "{{ request.object.metadata.namespace }}" }}
