apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ldap_connector
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}-ldap-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap_connector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ldap_connector
    spec:
      containers:
      - image: vividboarder/vaultwarden_ldap:0.6.2
        name: vaultwarden-ldap
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-ldap-config
        - configMapRef:
            name: {{ .Release.Name }}-ldap-config

        
