apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-ldap-config
data:
  APP_VAULTWARDEN_ADMIN_TOKEN: "{{ .Values.ldap.vaultwarden.admin_token | b64enc }}"
  APP_LDAP_BIND_PASSWORD: "{{ .Values.ldap.bind_password | b64enc }}"