apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich
data:
  ENABLE_MAPBOX: "false"
  NODE_ENV: "production"
  DISABLE_REVERSE_GEOCODING: "true"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  TYPESENSE_ENABLED: "true"