apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
data:
  ENABLE_MAPBOX: "false"
  NODE_ENV: "production"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  DB_DATABASE_NAME: "{{ .Values.db.name }}"
  DB_HOSTNAME: "{{ .Values.db.host }}"
  DB_USERNAME: "{{ .Values.db.username }}"
  REDIS_HOSTNAME: "{{ .Values.redis.host }}"
  REDIS_DBINDEX: "{{ .Values.redis.dbindex }}"