apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: immich-immich@kubernetescrd
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: immich-web
            port:
              number: 3000
        path: /
        pathType: Prefix
      - backend:
          service:
            name: immich-server
            port:
              number: 3001
        path: /api
        pathType: Prefix