apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: {{ .Values.persistence.storageclass }}