---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich
data:
  DB_PASSWORD: "{{ .Values.db.password | b64enc }}"
  JWT_SECRET: "{{ .Values.jwt | b64enc }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich-config
data:
  config.json: "{{ .Values.config | b64enc }}"