apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich
data:
  DB_DATABASE_NAME: "{{ .Values.db.name | b64enc }}"
  DB_HOSTNAME: "{{ .Values.db.host | b64enc }}"
  DB_PASSWORD: "{{ .Values.db.password | b64enc }}"
  DB_USERNAME: "{{ .Values.db.username | b64enc }}"
  JWT_SECRET: "{{ .Values.jwt | b64enc }}"
  REDIS_HOSTNAME: "{{ .Values.redis.host | b64enc }}"
  REDIS_DBINDEX: "{{ .Values.redis.dbindex | b64enc }}"
  TYPESENSE_API_KEY: "{{ .Values.typesense.api_key | b64enc }}"