apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich
data:
  DB_PASSWORD: "{{ .Values.db.password | b64enc }}"
  JWT_SECRET: "{{ .Values.jwt | b64enc }}"
  TYPESENSE_API_KEY: "{{ .Values.typesense.api_key | b64enc }}"