{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "common.names.fullname" . }}-private-key
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  private_key: {{ .Values.private_key | b64enc }}