apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich-server
    app.kubernetes.io/instance: immich