apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actualbudget-api
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: actualbudget-api-docs@kubernetescrd,actualbudget-api-v1@kubernetescrd
spec:
  rules:
    - host: budget.pajos.us
      http:
        paths:
          - backend:
              service:
                name: actualbudget-api
                port:
                  number: 5007
            path: /api
            pathType: Prefix
