apiVersion: v1
kind: Service
metadata:
  name: actualbudget-api
spec:
  ports:
    - name: http
      port: 5007
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/name: actualbudget
  type: ClusterIP