apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: {{ .Values.machinelearning.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-machine-learning
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-machine-learning
        app.kubernetes.io/instance: immich
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - immich-machine-learning
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: immich-immich-machine-learning
          image: "altran1502/immich-machine-learning:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: immich
            - configMapRef:
                name: immich
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
            - name: cache
              mountPath: /cache
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: '/ping'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: '/ping'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: '/ping'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
        - name: cache
          persistentVolumeClaim:
            claimName: immich-machine-learning-cache