apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-typesense
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-typesense
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-typesense
        app.kubernetes.io/instance: immich
    spec:
      containers:
        - name: immich-typesense
          image: "typesense/typesense:{{ .Values.typesense.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TYPESENSE_API_KEY
              value: "{{ .Values.typesense.api_key }}"
            - name: TYPESENSE_DATA_DIR
              value: "/data"
          ports:
            - name: http
              containerPort: 8108
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: '/health'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: '/health'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: '/health'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-typesense