apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-typesense
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.typesense.persistence.storageclass }}