apiVersion: v1
kind: Service
metadata:
  name: typesense
spec:
  type: ClusterIP
  ports:
  - port: 8108
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich-typesense
    app.kubernetes.io/instance: immich