apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservice
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-microservice
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-microservice
        app.kubernetes.io/instance: immich
    spec:
      containers:
        - name: immich-immich-microservice
          image: "altran1502/immich-server:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:       
            - ./start-microservices.sh
          envFrom:
            - secretRef:
                name: immich
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library