apiVersion: v1
kind: Service
metadata:
  name: immich-microservice
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich-microservice
    app.kubernetes.io/instance: immich