apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: sealed-secrets-key
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
stringData:
  tls.crt: |
{{ .Values.tls.crt | indent 4 }}
  tls.key: |
{{ .Values.tls.key | indent 4 }}