apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PAPERLESS_ADMIN_MAIL: "su.homeserver@gmail.com"
  PAPERLESS_ADMIN_USER: "{{ .Values.admin.user }}"
  PAPERLESS_DATA_DIR: "/data"
  PAPERLESS_DBHOST: "postgres.db"
  PAPERLESS_DBNAME: "paperlessngx"
  PAPERLESS_DBSSLMODE: "disable"
  PAPERLESS_DBUSER: "paperlessngx"
  PAPERLESS_EMAIL_FROM: "su.homeserver@gmail.com"
  PAPERLESS_EMAIL_HOST: "nodered-node-red.nodered"
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
  PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_FORWARDED_USER"
  PAPERLESS_LOGOUT_REDIRECT_URL: "https://docs.pajos.us/oauth2/sign_out"
  PAPERLESS_MEDIA_ROOT: "/media"
  PAPERLESS_PROXY_SSL_HEADER: "[\"HTTP_X_FORWARDED_PROTO\", \"https\"]"
  PAPERLESS_REDIS: "redis://redis-master.redis:6379"
  PAPERLESS_TIME_ZONE: "America/Phoenix"
  PAPERLESS_URL: "https://docs.pajos.us"
  PAPERLESS_USE_X_FORWARD_HOST: "true"
  PAPERLESS_USE_X_FORWARD_PORT: "true"
  USERMAP_GID: "1000"
  USERMAP_UID: "1000"