apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  PAPERLESS_ADMIN_MAIL: "{{ .Values.admin.mail }}"
  PAPERLESS_ADMIN_USER: "{{ .Values.admin.user }}"
  PAPERLESS_DATA_DIR: "/data"
  PAPERLESS_DBHOST: "{{ .Values.db.host }}"
  PAPERLESS_DBNAME: "{{ .Values.db.name }}"
  PAPERLESS_DBSSLMODE: "disable"
  PAPERLESS_DBUSER: "{{ .Values.db.user }}"
  PAPERLESS_EMAIL_FROM: "{{ .Values.mail.from }}"
  PAPERLESS_EMAIL_HOST: "{{ .Values.mail.host }}"
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
  PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_FORWARDED_USER"
  PAPERLESS_LOGOUT_REDIRECT_URL: "{{ .Values.logout_redirect_url }}"
  PAPERLESS_MEDIA_ROOT: "/media"
  PAPERLESS_PROXY_SSL_HEADER: "[\"HTTP_X_FORWARDED_PROTO\", \"https\"]"
  PAPERLESS_REDIS: "{{ .Values.redis_url }}"
  PAPERLESS_TIME_ZONE: "{{ .Values.TZ }}"
  PAPERLESS_URL: "https://{{ .Values.domain }}"
  PAPERLESS_USE_X_FORWARD_HOST: "true"
  PAPERLESS_USE_X_FORWARD_PORT: "true"
  USERMAP_GID: "{{ .Values.gid }}"
  USERMAP_UID: "{{ .Values.uid }}"