apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: "docs.pajos.us"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 4180