apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  PAPERLESS_ADMIN_PASSWORD: "vault:secret/data/k8s/shared/root#password"
  PAPERLESS_DBPASS: "vault:secret/data/k8s/paperlessngx/paperlessngx#db-password"
  PAPERLESS_SECRET_KEY: "vault:secret/data/k8s/shared/root#password"