{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  ddclient.conf: |
{{ .Values.config | b64enc | indent 4 }}