apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-web
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-web
        app.kubernetes.io/instance: immich
    spec:
      containers:
        - name: immich-immich-web
          image: "altran1502/immich-web:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: immich
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: '/'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: '/'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: '/'
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP