apiVersion: v1
kind: Service
metadata:
  name: immich-web
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich-web
    app.kubernetes.io/instance: immich