kind: ConfigMap
metadata:
  name: grafana-agent
apiVersion: v1
data:
  agent.yaml: |
{{ .Values.agent.config | toYaml | indent 4 }}
---
kind: ConfigMap
metadata:
  name: grafana-agent-logs
apiVersion: v1
data:
  agent.yaml: |
{{ .Values.logagent.config | toYaml | indent 4 }}