apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  addresses:
{{- range .Values.addresses }}
  - {{ . }}
{{- end }}